import type {
  AssessmentMethod,
  Baseline,
  ControlFamily,
  NistControl,
} from "./types";

function ctrl(
  id: string,
  family: ControlFamily,
  title: string,
  statement: string,
  discussion: string,
  baselines: Baseline[],
  related: string[],
  methods: AssessmentMethod[],
  evidenceHints: string[],
  parameters?: string[],
): NistControl {
  return {
    id,
    family,
    title,
    statement,
    discussion,
    baselines,
    related,
    methods,
    evidenceHints,
    parameters,
  };
}

export const NIST_CATALOG: NistControl[] = [
  ctrl("AC-1", "AC", "Policy and Procedures",
    "Develop, document, and disseminate access control policy and procedures; designate an official to manage the policy; review and update at an organization-defined frequency.",
    "Access control policy addresses purpose, scope, roles, and compliance. Procedures implement the policy across the authorization boundary.",
    ["low", "moderate", "high"], ["PM-9", "SI-12"], ["examine", "interview"],
    ["Access control policy", "Procedure set", "Review records"]),
  ctrl("AC-2", "AC", "Account Management",
    "Define account types; assign account managers; require approvals; specify authorizations; monitor usage; notify managers of transfers and terminations; review accounts; disable accounts of users posing significant risk within the defined period.",
    "Account management is the lifecycle of identity: creation, review, modification, disablement, and removal. Closely coupled with HR termination feeds and privileged access.",
    ["low", "moderate", "high"], ["AC-3", "AC-5", "AC-6", "IA-2", "IA-4", "IA-5", "IA-8", "PS-4"],
    ["examine", "interview", "test"],
    ["IdP account inventory", "HR termination feed", "Privileged account review", "Disablement tickets"],
    ["Account types", "Review frequency", "Disablement period"]),
  ctrl("AC-2(1)", "AC", "Automated System Account Management",
    "Support the management of system accounts using automated mechanisms.",
    "Automation reduces latency between HR events and account state. Typical evidence: SCIM, lifecycle workflows, Just-in-Time access.",
    ["moderate", "high"], ["AC-2", "IA-4"], ["examine", "test"],
    ["SCIM logs", "Lifecycle workflow", "IdP automation config"]),
  ctrl("AC-2(2)", "AC", "Automated Temporary and Emergency Account Management",
    "Automatically disable temporary and emergency accounts after an organization-defined time period.",
    "Emergency accounts are a frequent audit finding when they persist beyond the incident window.",
    ["moderate", "high"], ["AC-2"], ["examine", "test"],
    ["Break-glass account policy", "Auto-disable configuration"]),
  ctrl("AC-2(3)", "AC", "Disable Accounts",
    "Disable accounts within an organization-defined time period when the accounts have expired, are no longer associated with a user or individual, are in violation of organizational policy, or have been inactive for an organization-defined time period.",
    "Inactive and orphaned accounts are a leading cause of residual access after personnel changes.",
    ["moderate", "high"], ["AC-2", "PS-4"], ["examine", "test"],
    ["Inactivity policy", "Orphan account report"]),
  ctrl("AC-3", "AC", "Access Enforcement",
    "Enforce approved authorizations for logical access to information and system resources in accordance with applicable policy.",
    "Access enforcement is typically implemented via RBAC/ABAC, network ACLs, and application authorization checks.",
    ["low", "moderate", "high"], ["AC-2", "AC-4", "AC-5", "AC-6", "AC-16"],
    ["examine", "test"], ["IAM policies", "Application authZ tests", "ACL export"]),
  ctrl("AC-4", "AC", "Information Flow Enforcement",
    "Enforce approved authorizations for controlling the flow of information within the system and between connected systems based on organization-defined information flow control policies.",
    "Covers boundary protection, data-flow diagrams, and technical enforcement of permitted paths.",
    ["moderate", "high"], ["AC-3", "AC-17", "CA-3", "SC-7"], ["examine", "test"],
    ["Data-flow diagram", "SG/NSG rules", "CASB policy"]),
  ctrl("AC-5", "AC", "Separation of Duties",
    "Identify and document separation of duties of individuals; define system access authorizations to support separation of duties.",
    "Prevents a single individual from controlling an entire critical function (e.g., develop and deploy, request and approve).",
    ["moderate", "high"], ["AC-2", "AC-3", "AC-6"], ["examine", "interview"],
    ["SoD matrix", "Privileged role map"]),
  ctrl("AC-6", "AC", "Least Privilege",
    "Employ the principle of least privilege, allowing only authorized accesses for users (or processes acting on behalf of users) that are necessary to accomplish assigned organizational missions and business functions.",
    "Least privilege is assessed through privileged role reviews, standing vs. just-in-time access, and service-account scope.",
    ["moderate", "high"], ["AC-2", "AC-3", "AC-5", "CM-5"], ["examine", "interview", "test"],
    ["Privileged access review", "JIT access logs", "Service account inventory"]),
  ctrl("AC-6(1)", "AC", "Authorize Access to Security Functions",
    "Authorize access for organization-defined individuals or roles to organization-defined security functions and security-relevant information.",
    "Security functions include audit configuration, crypto key management, and identity administration.",
    ["moderate", "high"], ["AC-6"], ["examine"], ["Security function role list"]),
  ctrl("AC-7", "AC", "Unsuccessful Logon Attempts",
    "Enforce a limit of consecutive invalid logon attempts by a user during an organization-defined time period and automatically lock or delay the account.",
    "Lockout thresholds must balance brute-force resistance with denial-of-service risk.",
    ["low", "moderate", "high"], ["AC-2", "IA-5"], ["examine", "test"],
    ["IdP lockout policy", "Failed logon metrics"]),
  ctrl("AC-8", "AC", "System Use Notification",
    "Display an approved system use notification message before granting access, informing users of monitoring, authorized use, and that use constitutes consent.",
    "Banners must be approved by counsel and displayed on interactive systems.",
    ["low", "moderate", "high"], ["AC-14", "PL-4"], ["examine", "test"],
    ["Banner text approval", "Screenshot of logon banner"]),
  ctrl("AC-17", "AC", "Remote Access",
    "Establish and document usage restrictions, configuration requirements, and implementation guidance for each type of remote access allowed; authorize remote access prior to connection; route remote access through managed access control points.",
    "VPN, ZTNA, and privileged jump hosts are typical implementations.",
    ["low", "moderate", "high"], ["AC-2", "AC-3", "AC-19", "IA-2", "IA-3", "SC-7"],
    ["examine", "test"], ["VPN/ZTNA config", "Remote access policy", "Jump host inventory"]),
  ctrl("AC-18", "AC", "Wireless Access",
    "Establish usage restrictions and implementation guidance for wireless access; authorize wireless access prior to allowing such connections.",
    "Includes Wi-Fi, Bluetooth, and other RF interfaces in the authorization boundary.",
    ["low", "moderate", "high"], ["AC-17", "CA-9", "CM-7", "SC-8"], ["examine", "test"],
    ["Wireless policy", "WPA3/802.1X config"]),
  ctrl("AC-19", "AC", "Access Control for Mobile Devices",
    "Establish usage restrictions and implementation guidance for organization-controlled mobile devices; authorize connection of mobile devices.",
    "MDM/UEM enrollment, containerization, and remote wipe are typical evidence.",
    ["low", "moderate", "high"], ["AC-3", "AC-7", "AC-18", "CM-2", "MP-7", "SC-7"],
    ["examine", "test"], ["MDM compliance report", "Mobile device inventory"]),
  ctrl("AC-20", "AC", "Use of External Systems",
    "Establish terms and conditions consistent with trust relationships established with other organizations owning, operating, and/or maintaining external systems, allowing authorized individuals to access the system from external systems or process, store, or transmit organization-controlled information using external systems.",
    "Covers contractor laptops, SaaS, and interconnection agreements.",
    ["low", "moderate", "high"], ["AC-3", "CA-3", "PL-4", "SA-9"], ["examine"],
    ["ISA/MOU", "External system register"]),

  ctrl("AT-1", "AT", "Policy and Procedures",
    "Develop, document, and disseminate awareness and training policy and procedures; review and update at the defined frequency.",
    "Training policy defines role-based curricula and frequency.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["AT policy"]),
  ctrl("AT-2", "AT", "Literacy Training and Awareness",
    "Provide security and privacy literacy training to system users as part of initial training, when required by system changes, and at an organization-defined frequency thereafter; employ literacy techniques.",
    "Annual cyber awareness is necessary but not sufficient; role-based content is expected.",
    ["low", "moderate", "high"], ["AT-3", "AT-4", "IR-2", "PL-4"], ["examine", "interview"],
    ["Training completion records", "Curriculum"]),
  ctrl("AT-3", "AT", "Role-Based Training",
    "Provide role-based security and privacy training to personnel with assigned security and privacy roles and responsibilities before authorizing access or performing assigned duties, when required by system changes, and at an organization-defined frequency thereafter.",
    "ISSO, developer, admin, and AO roles require specialized training.",
    ["low", "moderate", "high"], ["AT-2", "AT-4"], ["examine"],
    ["Role curriculum", "Privileged user training records"]),
  ctrl("AT-4", "AT", "Training Records",
    "Document and monitor information security and privacy training activities, including basic security and privacy awareness training and specific information system security and privacy training; retain records for the defined period.",
    "LMS exports and completion percentages are typical evidence.",
    ["low", "moderate", "high"], ["AT-2", "AT-3"], ["examine"], ["LMS export"]),

  ctrl("AU-1", "AU", "Policy and Procedures",
    "Develop, document, and disseminate audit and accountability policy and procedures.",
    "Defines what is logged, how long it is retained, and who reviews it.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["AU policy"]),
  ctrl("AU-2", "AU", "Event Logging",
    "Identify the types of events that the system is capable of logging; coordinate logging with other organizational entities; determine events to be logged; specify content of audit records; provide a rationale for events selected.",
    "Must cover authentication, privilege use, security-relevant object access, and admin actions.",
    ["low", "moderate", "high"], ["AU-3", "AU-12", "SI-4"], ["examine", "test"],
    ["Logging standard", "SIEM source list"]),
  ctrl("AU-3", "AU", "Content of Audit Records",
    "Ensure that audit records contain information that establishes what type of event occurred, when, where, source, outcome, and identity of any individuals or subjects associated with the event.",
    "Incomplete audit content is a frequent assessment finding.",
    ["low", "moderate", "high"], ["AU-2", "AU-8", "AU-12"], ["examine", "test"],
    ["Sample audit records", "Log schema"]),
  ctrl("AU-4", "AU", "Audit Log Storage Capacity",
    "Allocate audit log storage capacity to accommodate organization-defined audit log retention requirements.",
    "Capacity planning must consider burst rates and retention.",
    ["low", "moderate", "high"], ["AU-2", "AU-5", "AU-9", "AU-11"], ["examine"],
    ["Retention config", "Storage capacity report"]),
  ctrl("AU-6", "AU", "Audit Record Review, Analysis, and Reporting",
    "Review and analyze system audit records at an organization-defined frequency for indications of organization-defined inappropriate or unusual activity; report findings to organization-defined personnel.",
    "Reviews may be automated via SIEM correlation, but human analysis of high-fidelity alerts is still required.",
    ["low", "moderate", "high"], ["AU-7", "IR-4", "SI-4"], ["examine", "interview", "test"],
    ["SIEM use cases", "Review tickets", "Alert metrics"]),
  ctrl("AU-8", "AU", "Time Stamps",
    "Use internal system clocks to generate time stamps for audit records; record time stamps that can be mapped to Coordinated Universal Time or Greenwich Mean Time.",
    "NTP/chrony configuration and drift monitoring are typical evidence.",
    ["low", "moderate", "high"], ["AU-3", "AU-12"], ["examine", "test"],
    ["NTP configuration", "Time sync status"]),
  ctrl("AU-9", "AU", "Protection of Audit Information",
    "Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
    "Write-once storage, index integrity, and privileged access to SIEM are in scope.",
    ["low", "moderate", "high"], ["AC-3", "AC-6", "AU-4", "AU-11"], ["examine", "test"],
    ["SIEM RBAC", "Log integrity config"]),
  ctrl("AU-12", "AU", "Audit Record Generation",
    "Provide audit record generation capability for the auditable events defined in AU-2; allow designated personnel to select which events are audited; generate audit records for events defined in AU-2.",
    "Must be demonstrated on representative components in the inventory.",
    ["low", "moderate", "high"], ["AU-2", "AU-3", "AU-6"], ["examine", "test"],
    ["Logging enabled on sample hosts", "CloudTrail/Activity Logs"]),

  ctrl("CA-1", "CA", "Policy and Procedures",
    "Develop, document, and disseminate assessment, authorization, and monitoring policy and procedures.",
    "This family operationalizes RMF steps Assess, Authorize, and Monitor.",
    ["low", "moderate", "high"], ["PM-9", "PM-10"], ["examine"], ["CA policy"]),
  ctrl("CA-2", "CA", "Control Assessments",
    "Develop a control assessment plan; assess the controls in the system and its environment of operation; produce a control assessment report; provide the results to designated officials.",
    "SP 800-53A methods (examine, interview, test) apply. Automation and continuous assessment are encouraged.",
    ["low", "moderate", "high"], ["CA-5", "CA-6", "CA-7", "PM-9", "RA-5"],
    ["examine", "interview"], ["SAP", "SAR", "Assessor independence statement"]),
  ctrl("CA-3", "CA", "Information Exchange",
    "Approve and manage the exchange of information between the system and other systems using interconnection security agreements or other exchange agreements; document interface characteristics, security and privacy requirements, and responsibilities.",
    "Interconnections must appear in the SSP and the inventory.",
    ["low", "moderate", "high"], ["AC-4", "AC-20", "CA-6", "PL-2", "SA-9"],
    ["examine"], ["ISA register", "Interface diagram"]),
  ctrl("CA-5", "CA", "Plan of Action and Milestones",
    "Develop a plan of action and milestones for the system to document the planned remedial actions to correct weaknesses or deficiencies noted during assessments and to reduce or eliminate identified vulnerabilities; update existing POA&M items.",
    "OSCAL POA&M is the machine-readable form of this artifact.",
    ["low", "moderate", "high"], ["CA-2", "CA-7", "PM-4", "SI-2"], ["examine"],
    ["POA&M register", "Milestone evidence"]),
  ctrl("CA-6", "CA", "Authorization",
    "Assign a senior official as the authorizing official; ensure the AO authorizes the system before operations and updates the authorization.",
    "The AO decision is a risk-based authorization to operate, not a certification of zero risk.",
    ["low", "moderate", "high"], ["CA-2", "CA-7", "PM-9", "PM-10"], ["examine"],
    ["Authorization letter", "Authorization package"]),
  ctrl("CA-7", "CA", "Continuous Monitoring",
    "Develop a system-level continuous monitoring strategy; implement monitoring in accordance with the organization-wide program; correlate monitoring information; respond to findings; report security and privacy status.",
    "The intent is ongoing authorization supported by live telemetry rather than point-in-time assessment only.",
    ["low", "moderate", "high"], ["AU-6", "CA-2", "CA-5", "PM-31", "RA-5", "SI-4"],
    ["examine", "test"], ["ConMon strategy", "Control status dashboard", "IACM metrics"]),
  ctrl("CA-8", "CA", "Penetration Testing",
    "Conduct penetration testing at an organization-defined frequency on organization-defined systems or system components.",
    "Required at High; often inherited from enterprise red team at Moderate.",
    ["high"], ["RA-5", "SA-11", "SI-2"], ["examine"], ["Pen-test report", "Remediation tracker"]),

  ctrl("CM-1", "CM", "Policy and Procedures",
    "Develop, document, and disseminate configuration management policy and procedures.",
    "Defines baselines, change control, and inventory.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["CM policy"]),
  ctrl("CM-2", "CM", "Baseline Configuration",
    "Develop, document, and maintain under configuration control a current baseline configuration of the system.",
    "Baselines may be CIS, DISA STIG, or organization-hardened images.",
    ["low", "moderate", "high"], ["CM-3", "CM-6", "CM-8", "SA-10"], ["examine", "test"],
    ["Golden image", "IaC baseline", "STIG checklist"]),
  ctrl("CM-3", "CM", "Configuration Change Control",
    "Determine and document types of changes; review proposed changes; approve or disapprove; document and implement approved changes; retain records; monitor and review activities.",
    "Change tickets, CAB, and GitOps PRs are typical evidence.",
    ["low", "moderate", "high"], ["CM-2", "CM-4", "CM-5", "SA-10"], ["examine"],
    ["Change tickets", "IaC pull requests"]),
  ctrl("CM-6", "CM", "Configuration Settings",
    "Establish and document configuration settings for components that reflect the most restrictive mode consistent with operational requirements; implement the settings; identify and document deviations; monitor and control changes.",
    "Configuration-as-code plus a compliance scanner (SCAP, CIS-CAT, Azure Policy, AWS Config) is the expected modern implementation.",
    ["low", "moderate", "high"], ["CM-2", "CM-3", "CM-7", "SI-4"], ["examine", "test"],
    ["Hardening baseline", "Compliance scan", "Deviation register"],
    ["Configuration checklist"]),
  ctrl("CM-7", "CM", "Least Functionality",
    "Configure the system to provide only mission-essential capabilities; prohibit or restrict the use of functions, ports, protocols, software, and services.",
    "Assessed via port scans, package inventories, and service allow-lists.",
    ["low", "moderate", "high"], ["CM-6", "CM-11", "RA-5"], ["examine", "test"],
    ["Port/protocol matrix", "Disabled service list"]),
  ctrl("CM-8", "CM", "System Component Inventory",
    "Develop and document an inventory of system components; review and update the inventory.",
    "The inventory is the backbone of the SSP, vulnerability management, and ConMon.",
    ["low", "moderate", "high"], ["CM-2", "CM-9", "PM-5"], ["examine", "test"],
    ["CMDB export", "Cloud inventory", "Agent inventory"]),
  ctrl("CM-10", "CM", "Software Usage Restrictions",
    "Use software and associated documentation in accordance with contract agreements and copyright laws; track the use of software and documentation protected by quantity licenses; control and document the use of peer-to-peer file sharing.",
    "License managers and software allow-lists support this control.",
    ["low", "moderate", "high"], ["CM-7", "CM-11", "SI-7"], ["examine"],
    ["Software allow-list", "License report"]),

  ctrl("CP-1", "CP", "Policy and Procedures",
    "Develop, document, and disseminate contingency planning policy and procedures.",
    "Aligns with FCD-1 / NIST SP 800-34.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["CP policy"]),
  ctrl("CP-2", "CP", "Contingency Plan",
    "Develop a contingency plan for the system that identifies essential missions and business functions, recovery objectives, restoration priorities, and roles; distribute; update; protect.",
    "The plan must match actual architecture, not a boilerplate template.",
    ["low", "moderate", "high"], ["CP-3", "CP-4", "CP-6", "CP-7", "CP-9", "CP-10", "IR-4"],
    ["examine", "interview"], ["Contingency plan", "RTO/RPO table"]),
  ctrl("CP-3", "CP", "Contingency Training",
    "Provide contingency training to system users consistent with assigned roles and responsibilities.",
    "Tabletop and technical recovery training both count.",
    ["low", "moderate", "high"], ["AT-3", "CP-2", "CP-4", "IR-2"], ["examine"],
    ["Training records"]),
  ctrl("CP-4", "CP", "Contingency Plan Testing",
    "Test the contingency plan using organization-defined tests; review test results; initiate corrective actions.",
    "Tests must exercise actual failover, not only a tabletop, at Moderate/High.",
    ["low", "moderate", "high"], ["CP-2", "CP-3", "IR-3"], ["examine"],
    ["Test after-action report"]),
  ctrl("CP-9", "CP", "System Backup",
    "Conduct backups of user-level, system-level, and security documentation information at organization-defined frequencies; protect the confidentiality, integrity, and availability of backup information.",
    "Immutable backups and restore tests are expected.",
    ["low", "moderate", "high"], ["CP-2", "CP-6", "CP-10", "MP-4", "SC-13"],
    ["examine", "test"], ["Backup job status", "Restore test"]),
  ctrl("CP-10", "CP", "System Recovery and Reconstitution",
    "Provide for recovery and reconstitution of the system to a known state after a disruption, compromise, or failure.",
    "Reconstitution includes integrity verification before returning to operations.",
    ["low", "moderate", "high"], ["CP-2", "CP-6", "CP-7", "CP-9", "SC-24"],
    ["examine"], ["Recovery runbook"]),

  ctrl("IA-1", "IA", "Policy and Procedures",
    "Develop, document, and disseminate identification and authentication policy and procedures.",
    "Covers authenticator management and federation.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["IA policy"]),
  ctrl("IA-2", "IA", "Identification and Authentication (Organizational Users)",
    "Uniquely identify and authenticate organizational users and associate that unique identification with processes acting on behalf of those users.",
    "Shared accounts for interactive users are not acceptable.",
    ["low", "moderate", "high"], ["AC-2", "AC-3", "AC-14", "IA-4", "IA-5", "IA-8"],
    ["examine", "test"], ["IdP unique ID config", "Shared account report"]),
  ctrl("IA-2(1)", "IA", "Multi-Factor Authentication to Privileged Accounts",
    "Implement multi-factor authentication for access to privileged accounts.",
    "Phishing-resistant MFA is preferred (PIV/FIDO2).",
    ["low", "moderate", "high"], ["IA-2", "IA-5"], ["examine", "test"],
    ["MFA enrollment report", "PIV/FIDO policy"]),
  ctrl("IA-2(2)", "IA", "Multi-Factor Authentication to Non-Privileged Accounts",
    "Implement multi-factor authentication for access to non-privileged accounts.",
    "Required at Moderate and High baselines.",
    ["moderate", "high"], ["IA-2"], ["examine", "test"], ["MFA coverage metrics"]),
  ctrl("IA-2(8)", "IA", "Access to Accounts — Replay Resistant",
    "Implement replay-resistant authentication mechanisms for access to accounts.",
    "FIDO2, PIV, and modern OIDC with nonce satisfy replay resistance.",
    ["moderate", "high"], ["IA-2"], ["examine", "test"], ["Authenticator types"]),
  ctrl("IA-4", "IA", "Identifier Management",
    "Manage system identifiers by receiving authorization to assign identifiers; selecting an identifier that identifies an individual, group, role, or device; assigning the identifier; preventing reuse for a defined period; disabling after a defined period of inactivity.",
    "Identifier reuse after termination is a common finding.",
    ["low", "moderate", "high"], ["AC-2", "IA-2", "IA-5", "IA-8"], ["examine"],
    ["Identifier policy", "Reuse settings"]),
  ctrl("IA-5", "IA", "Authenticator Management",
    "Manage system authenticators by verifying identity before issuance; establishing initial authenticator content; ensuring authenticators have sufficient strength; establishing procedures for lost/compromised/damaged authenticators; changing default authenticators; protecting authenticator content.",
    "Password policy is only one facet; hardware tokens, certificates, and secrets management are in scope.",
    ["low", "moderate", "high"], ["AC-3", "AC-6", "IA-2", "IA-4", "IA-7", "IA-8"],
    ["examine", "test"], ["Authenticator policy", "Secrets manager", "PIV issuance SOP"],
    ["Password complexity / authenticator strength"]),
  ctrl("IA-5(1)", "IA", "Password-Based Authentication",
    "For password-based authentication: maintain a list of commonly-used, expected, or compromised passwords and verify new passwords are not on the list; employ automated tools; enforce composition and lifetime per policy; store and transmit cryptographically protected passwords.",
    "NIST SP 800-63B is the current password guidance.",
    ["low", "moderate", "high"], ["IA-5"], ["examine", "test"],
    ["Password policy", "HIBP/banned-password config"]),
  ctrl("IA-8", "IA", "Identification and Authentication (Non-Organizational Users)",
    "Uniquely identify and authenticate non-organizational users or processes acting on behalf of non-organizational users.",
    "Federation, contractors, and public users are in scope.",
    ["low", "moderate", "high"], ["AC-2", "AC-14", "AC-17", "AC-18", "IA-2", "IA-4", "IA-5"],
    ["examine"], ["Federation config", "External user types"]),

  ctrl("IR-1", "IR", "Policy and Procedures",
    "Develop, document, and disseminate incident response policy and procedures.",
    "Aligns with NIST SP 800-61.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["IR policy"]),
  ctrl("IR-2", "IR", "Incident Response Training",
    "Provide incident response training to system users consistent with assigned roles and responsibilities.",
    "Includes tabletop and technical responder training.",
    ["low", "moderate", "high"], ["AT-3", "CP-3", "IR-3", "IR-4", "IR-9"],
    ["examine"], ["IR training records"]),
  ctrl("IR-4", "IR", "Incident Handling",
    "Implement an incident handling capability for incidents that includes preparation, detection and analysis, containment, eradication, and recovery; coordinate incident handling activities with contingency planning; incorporate lessons learned.",
    "Must be demonstrated with tickets and after-action reports, not only a policy.",
    ["low", "moderate", "high"], ["AU-6", "CM-6", "CP-2", "IR-5", "IR-6", "IR-8", "SI-4"],
    ["examine", "interview"], ["IR playbooks", "Incident tickets", "Lessons-learned"]),
  ctrl("IR-5", "IR", "Incident Monitoring",
    "Track and document incidents.",
    "Incident register with timelines, IOCs, and affected assets.",
    ["low", "moderate", "high"], ["AU-6", "IR-4", "IR-8", "SC-5", "SI-4"],
    ["examine"], ["Incident register"]),
  ctrl("IR-6", "IR", "Incident Reporting",
    "Require personnel to report suspected incidents to the organizational incident response capability within an organization-defined time period; report incident information to organization-defined authorities.",
    "US-CERT / CISA reporting timelines apply for federal systems.",
    ["low", "moderate", "high"], ["IR-4", "IR-8"], ["examine"],
    ["Reporting SOP", "CISA notification records"]),
  ctrl("IR-8", "IR", "Incident Response Plan",
    "Develop an incident response plan that provides the organization with a roadmap for implementing its incident response capability; distributes the plan; reviews and updates.",
    "The plan must name roles, communication paths, and severity criteria.",
    ["low", "moderate", "high"], ["IR-4", "IR-7"], ["examine"], ["IR plan"]),

  ctrl("MA-1", "MA", "Policy and Procedures",
    "Develop, document, and disseminate maintenance policy and procedures.",
    "Covers on-site, remote, and vendor maintenance.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["MA policy"]),
  ctrl("MA-2", "MA", "Controlled Maintenance",
    "Schedule, document, and review records of maintenance and repairs on system components; approve and monitor all maintenance activities; terminate connections when remote maintenance is complete.",
    "Change tickets should reference maintenance windows.",
    ["low", "moderate", "high"], ["CM-3", "CM-8", "MA-4", "MP-6", "PE-6", "SI-2"],
    ["examine"], ["Maintenance tickets"]),
  ctrl("MA-4", "MA", "Nonlocal Maintenance",
    "Approve and monitor nonlocal maintenance and diagnostic activities; allow the use of nonlocal maintenance and diagnostic tools only as consistent with policy; employ strong authenticators; terminate sessions and connections.",
    "Vendor remote access must be brokered and recorded.",
    ["low", "moderate", "high"], ["AC-3", "AC-6", "AC-17", "AU-2", "AU-3", "IA-2", "IA-5", "MA-5"],
    ["examine", "test"], ["Vendor remote access logs"]),

  ctrl("MP-1", "MP", "Policy and Procedures",
    "Develop, document, and disseminate media protection policy and procedures.",
    "Covers paper, removable, and digital media.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["MP policy"]),
  ctrl("MP-2", "MP", "Media Access",
    "Restrict access to digital and non-digital media to authorized individuals.",
    "Includes backup tapes, USB, and printed CUI.",
    ["low", "moderate", "high"], ["AC-3", "MP-4", "PE-2", "PE-3"], ["examine"],
    ["Media access log"]),
  ctrl("MP-6", "MP", "Media Sanitization",
    "Sanitize system media prior to disposal, release out of organizational control, or release for reuse using organization-defined sanitization techniques; employ sanitization mechanisms with the strength and integrity commensurate with the security or privacy risk.",
    "NIST SP 800-88 techniques apply. Cloud media sanitization is typically inherited.",
    ["low", "moderate", "high"], ["MA-2", "RA-3", "SC-4", "SI-12"], ["examine"],
    ["Sanitization SOP", "Destruction certificates"]),
  ctrl("MP-7", "MP", "Media Use",
    "Restrict or prohibit the use of organization-defined types of system media on organization-defined systems or system components using organization-defined restrictions.",
    "USB allow-listing and DLP are typical.",
    ["low", "moderate", "high"], ["AC-19", "CM-7", "PL-4"], ["examine", "test"],
    ["USB policy", "DLP/device control"]),

  ctrl("PE-1", "PE", "Policy and Procedures",
    "Develop, document, and disseminate physical and environmental protection policy and procedures.",
    "Often inherited from the hosting facility or cloud provider.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["PE policy", "FedRAMP inheritance"]),
  ctrl("PE-2", "PE", "Physical Access Authorizations",
    "Develop, approve, and maintain a list of individuals with authorized access to the facility where the system resides; issue authorization credentials; review the list.",
    "Data center and SCIF access lists.",
    ["low", "moderate", "high"], ["AT-3", "AU-2", "IA-4", "MP-2", "PE-3", "PE-4", "PS-3"],
    ["examine"], ["Access roster", "Badge report"]),
  ctrl("PE-3", "PE", "Physical Access Control",
    "Enforce physical access authorizations at entry/exit points; verify individual access authorizations before granting access; control ingress/egress with physical access devices and guards.",
    "May be fully inherited for cloud-hosted systems.",
    ["low", "moderate", "high"], ["AU-2", "AU-6", "MP-2", "PE-2", "PS-3"],
    ["examine"], ["Badge system", "Visitor log"]),
  ctrl("PE-6", "PE", "Monitoring Physical Access",
    "Monitor physical access to the facility where the system resides to detect and respond to physical security incidents.",
    "CCTV, door alarms, and SOC procedures.",
    ["low", "moderate", "high"], ["CA-7", "IR-4", "IR-6"], ["examine"],
    ["Physical monitoring SOP"]),

  ctrl("PL-1", "PL", "Policy and Procedures",
    "Develop, document, and disseminate planning policy and procedures.",
    "Covers SSP, rules of behavior, and architecture.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["PL policy"]),
  ctrl("PL-2", "PL", "System Security and Privacy Plans",
    "Develop security and privacy plans for the system that are consistent with the organization's enterprise architecture; explicitly define the authorization boundary; describe the operational context; provide the security and privacy categorization; describe how controls are implemented; are reviewed and approved.",
    "OSCAL SSP is the machine-readable form. The SSP must stay synchronized with the live environment.",
    ["low", "moderate", "high"], ["AC-2", "CA-3", "CM-8", "PL-7", "PL-8", "PM-9", "SA-5"],
    ["examine"], ["SSP", "OSCAL SSP", "Boundary diagram"]),
  ctrl("PL-4", "PL", "Rules of Behavior",
    "Establish and provide to individuals requiring access to the system, the rules that describe their responsibilities and expected behavior for information and system usage, security, and privacy; receive a signed acknowledgment.",
    "Often delivered through annual awareness with an attestation.",
    ["low", "moderate", "high"], ["AC-8", "AT-2", "PL-2", "PS-6"], ["examine"],
    ["RoB attestation records"]),
  ctrl("PL-8", "PL", "Security and Privacy Architectures",
    "Develop security and privacy architectures for the system that describe the requirements and allocation of controls to system components; define where controls are implemented; describe relationships with enterprise architecture.",
    "Architecture diagrams and control allocation (common / system / hybrid / inherited) live here.",
    ["moderate", "high"], ["PL-2", "PM-7", "SA-8", "SC-2"], ["examine"],
    ["Architecture package", "Control allocation"]),

  ctrl("PM-1", "PM", "Information Security Program Plan",
    "Develop and disseminate an organization-wide information security program plan.",
    "Program-level; often inherited by systems.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["Program plan"]),
  ctrl("PM-4", "PM", "Plan of Action and Milestones Process",
    "Implement a process for ensuring that POA&M items for the security and privacy programs and associated systems are maintained; review for consistency with risk tolerance.",
    "Enterprise POA&M process that system ISSOs execute.",
    ["low", "moderate", "high"], ["CA-5", "PM-9"], ["examine"], ["POA&M SOP"]),
  ctrl("PM-9", "PM", "Risk Management Strategy",
    "Develop a comprehensive strategy to manage security and privacy risk; implement the strategy consistently across the organization; review and update.",
    "NIST SP 800-37 and 800-30 are the methodological backbone.",
    ["low", "moderate", "high"], ["PM-8", "PM-28", "RA-3"], ["examine"],
    ["Risk strategy", "Risk appetite statement"]),
  ctrl("PM-10", "PM", "Authorization Process",
    "Manage the security and privacy state of organizational systems and the environments in which those systems operate through authorization processes; designate authorizing officials; implement a process for ensuring authorizing officials complete authorization packages.",
    "Defines AO authority and package contents.",
    ["low", "moderate", "high"], ["CA-6", "PM-9"], ["examine"], ["Authorization SOP"]),

  ctrl("PS-1", "PS", "Policy and Procedures",
    "Develop, document, and disseminate personnel security policy and procedures.",
    "Screening, onboarding, transfer, and termination.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["PS policy"]),
  ctrl("PS-2", "PS", "Position Risk Designation",
    "Assign a risk designation to all organizational positions; establish screening criteria for individuals filling those positions; review and update position risk designations.",
    "Position designation drives investigation level.",
    ["low", "moderate", "high"], ["PS-3"], ["examine"], ["Position designations"]),
  ctrl("PS-3", "PS", "Personnel Screening",
    "Screen individuals prior to authorizing access; rescreen in accordance with organization-defined conditions.",
    "Background investigation evidence is typically inherited from HR/security office.",
    ["low", "moderate", "high"], ["AC-2", "IA-4", "PS-2", "PS-6"], ["examine"],
    ["Screening completion"]),
  ctrl("PS-4", "PS", "Personnel Termination",
    "Upon termination: disable system access within an organization-defined time period; terminate or revoke authenticators; retrieve security-related organizational property; retain access to organizational information and systems formerly controlled by terminated individual.",
    "This control is the usual root cause when AC-2 fails.",
    ["low", "moderate", "high"], ["AC-2", "IA-4", "PS-5"], ["examine", "test"],
    ["Termination checklist", "Disablement SLO report"]),
  ctrl("PS-5", "PS", "Personnel Transfer",
    "Review and confirm ongoing operational need for current logical and physical access authorizations to systems and facilities when individuals are reassigned or transferred; initiate transfer or reassignment actions; modify access.",
    "Transfers without access recertification create standing privilege.",
    ["low", "moderate", "high"], ["AC-2", "PS-4"], ["examine"],
    ["Transfer recertification"]),

  ctrl("PT-1", "PT", "Policy and Procedures",
    "Develop, document, and disseminate policy and procedures for PII processing and transparency.",
    "Rev. 5 privacy family; applies when PII is processed.",
    ["low", "moderate", "high"], ["PM-9", "PT-2"], ["examine"], ["Privacy policy"]),
  ctrl("PT-2", "PT", "Authority to Process Personally Identifiable Information",
    "Determine and document the authority that permits the processing of PII; restrict processing to only that which is authorized.",
    "SORN, PIA, and statutory authority.",
    ["low", "moderate", "high"], ["PT-3", "RA-8"], ["examine"],
    ["SORN", "PIA", "Authority memo"]),
  ctrl("PT-3", "PT", "Personally Identifiable Information Processing Purposes",
    "Identify and document the purpose for processing PII; describe the purpose in privacy notices and policies; restrict processing to only that which is compatible with the identified purpose.",
    "Purpose specification and use limitation.",
    ["low", "moderate", "high"], ["PT-2", "PT-5"], ["examine"], ["Purpose statements"]),

  ctrl("RA-1", "RA", "Policy and Procedures",
    "Develop, document, and disseminate risk assessment policy and procedures.",
    "Methodology typically follows NIST SP 800-30.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["RA policy"]),
  ctrl("RA-2", "RA", "Security Categorization",
    "Categorize the system and information processed, stored, and transmitted; document the security categorization results, including supporting rationale, in the SSP; verify the authorizing official or designated representative reviews and approves the categorization.",
    "FIPS 199 / SP 800-60. High-water mark of confidentiality, integrity, availability.",
    ["low", "moderate", "high"], ["CM-8", "PL-2", "RA-3", "SA-8"], ["examine"],
    ["FIPS 199 worksheet", "Data types"]),
  ctrl("RA-3", "RA", "Risk Assessment",
    "Conduct a risk assessment, including identifying threats and vulnerabilities, determining likelihood and impact, determining risk; document; review; update; disseminate.",
    "Must be current with architecture and threat landscape, not a static PDF.",
    ["low", "moderate", "high"], ["CA-2", "PM-9", "RA-2", "RA-5", "RA-7"],
    ["examine"], ["Risk assessment report"]),
  ctrl("RA-5", "RA", "Vulnerability Monitoring and Scanning",
    "Monitor and scan for vulnerabilities in the system and hosted applications at an organization-defined frequency and when new vulnerabilities potentially affecting the system are identified; remediate vulnerabilities in accordance with an organizational assessment of risk; share information obtained from the vulnerability scanning process and security control assessments.",
    "Must cover hosts, containers, IaC, and dependencies. CISA KEV items require accelerated handling.",
    ["low", "moderate", "high"], ["CA-2", "CA-7", "CM-6", "CM-8", "RA-3", "SI-2", "SI-3"],
    ["examine", "test"], ["Scan reports", "KEV tracker", "Coverage map"],
    ["Scan frequency"]),
  ctrl("RA-5(2)", "RA", "Update Vulnerabilities to Be Scanned",
    "Update the system vulnerabilities to be scanned when new vulnerabilities are identified and reported.",
    "Plugin/feed currency of the scanner.",
    ["low", "moderate", "high"], ["RA-5", "SI-5"], ["examine", "test"],
    ["Scanner plugin age"]),
  ctrl("RA-7", "RA", "Risk Response",
    "Respond to findings from security and privacy assessments, monitoring, and audits in accordance with organizational risk tolerance.",
    "Response may be remediate, mitigate, accept, or transfer — with AO concurrence for residual risk.",
    ["low", "moderate", "high"], ["CA-5", "PM-4", "PM-9", "RA-3", "SR-2"],
    ["examine"], ["Risk response decisions"]),
  ctrl("RA-9", "RA", "Criticality Analysis",
    "Identify critical system components and functions by performing a criticality analysis for organization-defined systems, system components, or system services at organization-defined decision points in the system development life cycle.",
    "Feeds contingency priorities and supply-chain protection.",
    ["moderate", "high"], ["CP-2", "PL-8", "PM-1", "SA-15", "SR-5"],
    ["examine"], ["Criticality analysis"]),

  ctrl("SA-1", "SA", "Policy and Procedures",
    "Develop, document, and disseminate system and services acquisition policy and procedures.",
    "Includes DevSecOps and vendor assessment.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["SA policy"]),
  ctrl("SA-3", "SA", "System Development Life Cycle",
    "Acquire, develop, and manage the system using a system development life cycle that incorporates security and privacy considerations; define and document information security and privacy roles and responsibilities throughout the SDLC; identify individuals having those roles.",
    "Secure SDLC, threat modeling, and gated releases.",
    ["low", "moderate", "high"], ["PL-8", "SA-4", "SA-8", "SA-11", "SA-15"],
    ["examine"], ["SDLC SOP", "Pipeline stages"]),
  ctrl("SA-4", "SA", "Acquisition Process",
    "Include the following requirements, descriptions, and criteria, explicitly or by reference, in the acquisition contract for the system, system component, or system service: security and privacy functional requirements; strength of mechanism; assurance; controls; documentation.",
    "FedRAMP, CMMC, and SCRM clauses live here.",
    ["low", "moderate", "high"], ["CM-8", "PS-7", "SA-3", "SA-5", "SA-8", "SA-9", "SA-11", "SR-5"],
    ["examine"], ["Contract clauses", "FedRAMP package ID"]),
  ctrl("SA-8", "SA", "Security and Privacy Engineering Principles",
    "Apply organization-defined security and privacy engineering principles in the specification, design, development, implementation, and modification of the system and system components.",
    "NIST SP 800-160 principles: isolation, least privilege, fail-safe, mediation.",
    ["low", "moderate", "high"], ["PL-8", "SA-3", "SA-4", "SA-15", "SC-2", "SC-3"],
    ["examine"], ["Design reviews"]),
  ctrl("SA-9", "SA", "External System Services",
    "Require that providers of external system services comply with organizational security and privacy requirements; define and document government oversight and user roles; employ processes to monitor security and privacy control compliance by external service providers.",
    "SaaS, IaaS, PaaS, and contractors. Inheritance from FedRAMP is documented here.",
    ["low", "moderate", "high"], ["CA-3", "IR-7", "PL-2", "PS-7", "SA-4"],
    ["examine"], ["FedRAMP inheritance", "Vendor ConMon"]),
  ctrl("SA-11", "SA", "Developer Testing and Evaluation",
    "Require the developer of the system, system component, or system service to provide a plan for ongoing security and privacy assessments; perform testing/evaluation; produce evidence of the execution of the assessment plan.",
    "SAST, DAST, SCA, and unit/integration tests mapped to controls.",
    ["moderate", "high"], ["CA-2", "SA-3", "SA-4", "SA-5", "SI-2"],
    ["examine", "test"], ["Pipeline scan results", "Coverage report"]),

  ctrl("SC-1", "SC", "Policy and Procedures",
    "Develop, document, and disseminate system and communications protection policy and procedures.",
    "Boundary, crypto, and isolation.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["SC policy"]),
  ctrl("SC-7", "SC", "Boundary Protection",
    "Monitor and control communications at the external managed interfaces to the system and at key internal managed interfaces; implement subnetworks for publicly accessible system components that are physically or logically separated from internal organizational networks; connect to external networks or systems only through managed interfaces consisting of boundary protection devices arranged in accordance with an organizational security and privacy architecture.",
    "Firewalls, WAF, API gateways, private endpoints, and zero-trust segmentation.",
    ["low", "moderate", "high"], ["AC-4", "AC-17", "CA-3", "CM-7", "IR-4", "RA-3", "SC-5"],
    ["examine", "test"], ["Network diagrams", "SG/NSG/firewall rules", "Private endpoint inventory"]),
  ctrl("SC-7(3)", "SC", "Access Points",
    "Limit the number of external network connections to the system.",
    "Minimize and inventory ingress/egress points.",
    ["moderate", "high"], ["SC-7"], ["examine", "test"], ["Ingress inventory"]),
  ctrl("SC-8", "SC", "Transmission Confidentiality and Integrity",
    "Protect the confidentiality and integrity of transmitted information.",
    "TLS 1.2+ in transit; approved cryptographic modules.",
    ["moderate", "high"], ["AC-17", "SC-12", "SC-13"], ["examine", "test"],
    ["TLS policy", "Certificate inventory"]),
  ctrl("SC-12", "SC", "Cryptographic Key Establishment and Management",
    "Establish and manage cryptographic keys when cryptography is employed in the system in accordance with the following key management requirements: organization-defined requirements for key generation, distribution, storage, access, and destruction.",
    "KMS/HSM, key rotation, and dual control.",
    ["low", "moderate", "high"], ["SC-8", "SC-13", "SC-17"], ["examine"],
    ["KMS config", "Key rotation policy"]),
  ctrl("SC-13", "SC", "Cryptographic Protection",
    "Determine the organization-defined cryptographic uses; implement the types of cryptography required for each specified cryptographic use.",
    "FIPS 140-validated modules for federal systems.",
    ["low", "moderate", "high"], ["AC-19", "SC-8", "SC-12"], ["examine", "test"],
    ["FIPS module inventory"]),
  ctrl("SC-28", "SC", "Protection of Information at Rest",
    "Protect the confidentiality and integrity of organization-defined information at rest.",
    "Volume encryption, object-lock, and application-level encryption.",
    ["moderate", "high"], ["AC-3", "AC-6", "CA-5", "CM-3", "SC-12", "SC-13", "SC-34"],
    ["examine", "test"], ["Encryption at rest config"]),
  ctrl("SC-39", "SC", "Process Isolation",
    "Maintain a separate execution domain for each executing system process.",
    "OS and container isolation; supporting hypervisor inheritance.",
    ["low", "moderate", "high"], ["AC-3", "SC-2", "SC-3"], ["examine"],
    ["Isolation architecture"]),

  ctrl("SI-1", "SI", "Policy and Procedures",
    "Develop, document, and disseminate system and information integrity policy and procedures.",
    "Flaw remediation, malware, and monitoring.",
    ["low", "moderate", "high"], ["PM-9"], ["examine"], ["SI policy"]),
  ctrl("SI-2", "SI", "Flaw Remediation",
    "Identify, report, and correct system flaws; test software and firmware updates related to flaw remediation for effectiveness and potential side effects before installation; install security-relevant updates within organization-defined time periods; incorporate flaw remediation into the configuration management process.",
    "Patch SLOs by severity, including CISA BOD / KEV timelines.",
    ["low", "moderate", "high"], ["CA-5", "CM-3", "CM-4", "MA-2", "RA-5", "SA-11", "SI-3", "SI-5"],
    ["examine", "test"], ["Patch SLO report", "Unpatched critical list", "Change tickets"]),
  ctrl("SI-3", "SI", "Malicious Code Protection",
    "Implement malicious code protection mechanisms at system entry and exit points to detect and eradicate malicious code; update malicious code protection mechanisms whenever new releases are available; configure to perform periodic scans and real-time scans of files from external sources.",
    "EDR plus content-scanning at email/web gateways.",
    ["low", "moderate", "high"], ["CM-3", "MA-4", "RA-5", "SC-7", "SI-2", "SI-4", "SI-8"],
    ["examine", "test"], ["EDR coverage", "Malware detections"]),
  ctrl("SI-4", "SI", "System Monitoring",
    "Monitor the system to detect attacks and indicators of potential attacks; identify unauthorized use; invoke monitoring as required; analyze detected events; determine organization-defined information of interest; protect information obtained from monitoring.",
    "EDR, SIEM, NDR, and cloud detection services. Feeds CA-7 and IR-4.",
    ["low", "moderate", "high"], ["AC-2", "AU-2", "AU-6", "AU-12", "CA-7", "IR-4", "RA-5", "SC-7"],
    ["examine", "test"], ["Detection coverage map", "Use-case catalog", "Alert metrics"]),
  ctrl("SI-5", "SI", "Security Alerts, Advisories, and Directives",
    "Receive system security alerts, advisories, and directives from organization-defined external organizations; generate internal security alerts, advisories, and directives as deemed necessary; disseminate; implement directives in accordance with established time frames.",
    "CISA, vendor PSIRT, and internal threat intel.",
    ["low", "moderate", "high"], ["RA-5", "SI-2"], ["examine"],
    ["Advisory intake SOP", "KEV handling"]),
  ctrl("SI-7", "SI", "Software, Firmware, and Information Integrity",
    "Employ integrity verification tools to detect unauthorized changes to organization-defined software, firmware, and information; take organization-defined actions when unauthorized changes are detected.",
    "File integrity monitoring, signed images, and admission controllers.",
    ["moderate", "high"], ["CM-3", "CM-8", "SA-10", "SC-8", "SC-13", "SI-3"],
    ["examine", "test"], ["FIM config", "Image signing"]),
  ctrl("SI-10", "SI", "Information Input Validation",
    "Check the validity of information inputs.",
    "Application-level validation, WAF, and schema enforcement.",
    ["moderate", "high"], ["SI-3", "SI-7", "SI-15"], ["examine", "test"],
    ["Input validation tests", "WAF rules"]),
  ctrl("SI-12", "SI", "Information Management and Retention",
    "Manage and retain information within the system and information output from the system in accordance with applicable laws, executive orders, directives, regulations, policies, standards, guidelines and operational requirements.",
    "Records schedules and data retention in cloud stores.",
    ["low", "moderate", "high"], ["AC-16", "AU-5", "AU-11", "MP-6", "SI-18"],
    ["examine"], ["Retention schedule"]),

  ctrl("SR-1", "SR", "Policy and Procedures",
    "Develop, document, and disseminate supply chain risk management policy and procedures.",
    "Rev. 5 family addressing suppliers, developers, and integrators.",
    ["low", "moderate", "high"], ["PM-9", "PM-30", "SR-2"], ["examine"], ["SCRM policy"]),
  ctrl("SR-2", "SR", "Supply Chain Risk Management Plan",
    "Develop a plan for managing supply chain risks associated with the research and development, design, manufacturing, acquisition, delivery, integration, operations and maintenance, and disposal of systems, system components, or system services; implement; review and update.",
    "Must identify critical suppliers and inspection points.",
    ["low", "moderate", "high"], ["PM-9", "PM-30", "RA-3", "RA-9", "SA-9", "SR-3"],
    ["examine"], ["SCRM plan"]),
  ctrl("SR-3", "SR", "Supply Chain Controls and Processes",
    "Establish a process for identifying and addressing weaknesses or deficiencies in the supply chain elements and processes; employ a supplier assessment process; use the acquisition process to require supply chain controls.",
    "Questionnaires, SBOMs, and on-site assessments.",
    ["low", "moderate", "high"], ["RA-3", "SA-4", "SA-9", "SR-2", "SR-6"],
    ["examine"], ["Supplier assessments", "SBOM"]),
  ctrl("SR-5", "SR", "Acquisition Strategies, Tools, and Methods",
    "Employ acquisition strategies, contract tools, and procurement methods to protect against, identify, and mitigate supply chain risks.",
    "Approved vendor lists, origin analysis, and escrow.",
    ["low", "moderate", "high"], ["SA-4", "SR-2", "SR-3"], ["examine"],
    ["Acquisition clauses"]),
  ctrl("SR-6", "SR", "Supplier Assessments and Reviews",
    "Assess and review the supply chain-related processes of suppliers prior to entering into a contractual agreement to acquire systems, system components, or system services; reassess at an organization-defined frequency.",
    "Stale supplier assessments are a common High finding.",
    ["moderate", "high"], ["RA-3", "SA-9", "SR-2", "SR-3"], ["examine"],
    ["Supplier assessment register"]),
];

export const CONTROL_BY_ID: Record<string, NistControl> = Object.fromEntries(
  NIST_CATALOG.map((c) => [c.id, c]),
);

export function familyOf(controlId: string): ControlFamily {
  return controlId.split("-")[0] as ControlFamily;
}

export function controlsInFamily(family: ControlFamily): NistControl[] {
  return NIST_CATALOG.filter((c) => c.family === family);
}

export function controlsForBaseline(baseline: Baseline): NistControl[] {
  return NIST_CATALOG.filter((c) => c.baselines.includes(baseline));
}
