export interface EvidenceMapping {
  source: string;
  controls: string[];
  authority: string;
  confidence: number;
}

export const EVIDENCE_MAPPINGS: EvidenceMapping[] = [
  {
    source: "AWS Config",
    controls: ["CM-6", "CM-2", "AC-3", "SC-7", "AU-12"],
    authority: "Control overlay — cloud config rules",
    confidence: 92,
  },
  {
    source: "AWS IAM",
    controls: ["AC-2", "AC-3", "AC-6", "IA-2", "IA-5"],
    authority: "Identity evidence",
    confidence: 95,
  },
  {
    source: "Entra ID",
    controls: ["AC-2", "AC-2(1)", "AC-2(3)", "IA-2", "IA-2(1)", "IA-2(2)", "PS-4"],
    authority: "Identity lifecycle",
    confidence: 96,
  },
  {
    source: "Tenable",
    controls: ["RA-5", "RA-5(2)", "SI-2", "CM-8"],
    authority: "Vulnerability scanner",
    confidence: 94,
  },
  {
    source: "Qualys",
    controls: ["RA-5", "SI-2", "CM-6"],
    authority: "Vulnerability / policy scan",
    confidence: 90,
  },
  {
    source: "Splunk",
    controls: ["AU-2", "AU-3", "AU-6", "AU-12", "IR-4", "SI-4"],
    authority: "SIEM",
    confidence: 91,
  },
  {
    source: "Microsoft Sentinel",
    controls: ["AU-6", "IR-4", "SI-4", "CA-7"],
    authority: "Cloud SIEM",
    confidence: 90,
  },
  {
    source: "CrowdStrike",
    controls: ["SI-3", "SI-4", "IR-4", "IR-5"],
    authority: "EDR",
    confidence: 93,
  },
  {
    source: "Wiz",
    controls: ["CM-6", "RA-5", "SC-7", "SC-28", "SI-2"],
    authority: "CNAPP",
    confidence: 89,
  },
  {
    source: "GitHub Advanced Security",
    controls: ["SA-11", "SI-2", "RA-5", "CM-3"],
    authority: "Code scanning",
    confidence: 88,
  },
  {
    source: "ServiceNow",
    controls: ["CM-3", "IR-4", "CA-5", "MA-2", "PS-4"],
    authority: "ITSM / tickets",
    confidence: 87,
  },
  {
    source: "Terraform state",
    controls: ["CM-2", "CM-6", "CM-8", "SC-7"],
    authority: "Infrastructure as code",
    confidence: 90,
  },
  {
    source: "Aegis 800-53A workbench",
    controls: ["CA-2", "CA-7", "PL-2", "AC-3", "SI-2"],
    authority: "Native SAR · examine / interview / test",
    confidence: 94,
  },
  {
    source: "ACAS",
    controls: ["RA-5", "RA-5(2)", "SI-2", "CM-8"],
    authority: "DoD authenticated vulnerability scan",
    confidence: 95,
  },
  {
    source: "STIG / SCAP",
    controls: ["CM-6", "CM-2", "CM-3", "SI-2"],
    authority: "DISA STIG checklist",
    confidence: 93,
  },
  {
    source: "Nmap",
    controls: ["CM-8", "SC-7", "RA-5", "CA-3"],
    authority: "Network discovery / listeners",
    confidence: 88,
  },
  {
    source: "ETEC",
    controls: ["CA-2", "CA-8", "SA-11", "SI-6"],
    authority: "Evaluation test engine",
    confidence: 86,
  },
  {
    source: "Network scanner",
    controls: ["SC-7", "CM-8", "SC-5", "CA-3"],
    authority: "Attach your network scanner",
    confidence: 85,
  },
  {
    source: "Application scanner",
    controls: ["SA-11", "SI-10", "RA-5", "SC-8"],
    authority: "Attach your application scanner",
    confidence: 85,
  },
  {
    source: "AXIOM DAST (S2)",
    controls: ["SA-11", "SI-10", "AC-3", "SC-7", "SC-8"],
    authority: "AXIOM Security Intelligence v2 · CWE catalog",
    confidence: 91,
  },
  {
    source: "AXIOM SCA",
    controls: ["RA-5", "SI-2", "SR-3", "SA-15"],
    authority: "Software composition · CVE / SBOM",
    confidence: 92,
  },
  {
    source: "AXIOM IaC",
    controls: ["CM-6", "SC-7", "AC-3", "SC-28", "AU-12"],
    authority: "Terraform Checkov / tfsec / OPA",
    confidence: 90,
  },
];

export const AGENTS = [
  {
    id: "rmf-orchestrator",
    name: "RMF Orchestrator",
    lane: "RMF",
    rmfStep: "prepare",
    summary: "Master agent for Prepare through Monitor. Delegates to specialists.",
  },
  {
    id: "ssp",
    name: "SSP Agent",
    lane: "RMF",
    rmfStep: "select",
    summary: "Drafts and maintains the OSCAL system security plan from live inventory.",
  },
  {
    id: "categorize",
    name: "Categorization Agent",
    lane: "RMF",
    rmfStep: "categorize",
    summary: "Proposes FIPS 199 impact from data types and mission context.",
  },
  {
    id: "assessment",
    name: "Assessment Agent",
    lane: "Assess",
    rmfStep: "assess",
    summary: "Executes 800-53A examine / interview / test procedures.",
  },
  {
    id: "evidence",
    name: "Evidence Agent",
    lane: "Assess",
    rmfStep: "assess",
    summary: "Collects artifacts, hashes them, and binds them to controls.",
  },
  {
    id: "poam",
    name: "POA&M Agent",
    lane: "Compliance",
    rmfStep: "authorize",
    summary: "Opens, ages, and closes plan-of-action items from findings.",
  },
  {
    id: "vuln",
    name: "Vulnerability Agent",
    lane: "Security",
    rmfStep: "monitor",
    summary: "Ingests scanner results, maps CVEs to controls, and scores mission risk.",
  },
  {
    id: "cloud",
    name: "Cloud Agent",
    lane: "Security",
    rmfStep: "implement",
    summary: "Reads AWS / Azure / GCP posture and maps to 800-53.",
  },
  {
    id: "config",
    name: "Configuration Agent",
    lane: "Security",
    rmfStep: "implement",
    summary: "Evaluates STIG / CIS / policy deviations against CM-6.",
  },
  {
    id: "siem",
    name: "SIEM Agent",
    lane: "Security",
    rmfStep: "monitor",
    summary: "Queries detections and audit coverage for AU and IR families.",
  },
  {
    id: "monitor",
    name: "Continuous Monitoring Agent",
    lane: "Monitor",
    rmfStep: "monitor",
    summary: "Keeps control status current from telemetry rather than last assessment.",
  },
  {
    id: "audit",
    name: "Audit Agent",
    lane: "Compliance",
    rmfStep: "authorize",
    summary: "Produces an explainable, citable decision record for every conclusion.",
  },
  {
    id: "twin",
    name: "Digital Twin Agent",
    lane: "Twin",
    rmfStep: "monitor",
    summary: "Keeps the live graph of apps, hosts, data, users, controls, and vulns.",
  },
  {
    id: "attack-path",
    name: "Attack-Path Agent",
    lane: "Security",
    rmfStep: "monitor",
    summary: "Walks vuln → asset → control → POA&M → ATO impact. Never authorizes.",
  },
  {
    id: "whatif",
    name: "What-If Simulator",
    lane: "RMF",
    rmfStep: "monitor",
    summary: "Simulates MFA off, cloud move, exposure, EDR swap without changing the record.",
  },
  {
    id: "assessor-copilot",
    name: "Assessor Copilot",
    lane: "Assess",
    rmfStep: "assess",
    summary: "Cites evidence against 800-53A objectives. Assessor decides.",
  },
  {
    id: "cato",
    name: "cATO Engine",
    lane: "Monitor",
    rmfStep: "monitor",
    summary: "ConMon → impact → human review. Does not issue ATO.",
  },
  {
    id: "k8s",
    name: "Kubernetes Agent",
    lane: "Security",
    rmfStep: "implement",
    summary: "Cluster objects mapped to 800-53.",
  },
  {
    id: "supply",
    name: "Supply-Chain Agent",
    lane: "Security",
    rmfStep: "monitor",
    summary: "SBOM, vendors, C-SCRM, contractual obligations.",
  },
  {
    id: "zt",
    name: "Zero Trust Agent",
    lane: "Security",
    rmfStep: "select",
    summary: "Seven CISA pillars onto 800-53.",
  },
] as const;

export const TOOL_REGISTRY = [
  { id: "aws.get_iam_users", domain: "AWS" },
  { id: "aws.get_security_groups", domain: "AWS" },
  { id: "aws.get_config_rules", domain: "AWS" },
  { id: "azure.get_policy_results", domain: "Azure" },
  { id: "azure.get_resources", domain: "Azure" },
  { id: "tenable.get_vulnerabilities", domain: "Vuln" },
  { id: "splunk.search", domain: "SIEM" },
  { id: "crowdstrike.get_detections", domain: "EDR" },
  { id: "servicenow.get_tickets", domain: "ITSM" },
  { id: "github.get_alerts", domain: "Code" },
  { id: "kubernetes.get_pods", domain: "K8s" },
  { id: "terraform.get_state", domain: "IaC" },
] as const;
