/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AtoRouteImport } from './routes/ato'
import { Route as AttackRouteImport } from './routes/attack'
import { Route as CatoRouteImport } from './routes/cato'
import { Route as CycleRouteImport } from './routes/cycle'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ImplementationRouteImport } from './routes/implementation'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InheritanceRouteImport } from './routes/inheritance'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as PoamRouteImport } from './routes/poam'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as PrepareRouteImport } from './routes/prepare'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as VulnerabilitiesRouteImport } from './routes/vulnerabilities'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ZeroTrustRouteImport } from './routes/zero-trust'
import { Route as ControlsIndexRouteImport } from './routes/controls/index'
import { Route as ControlsControlIdRouteImport } from './routes/controls/$controlId'
import { Route as SystemsIndexRouteImport } from './routes/systems/index'
import { Route as SystemsSystemIdRouteImport } from './routes/systems/$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AtoRoute = AtoRouteImport.update({
  id: '/ato',
  path: '/ato',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackRoute = AttackRouteImport.update({
  id: '/attack',
  path: '/attack',
  getParentRoute: () => rootRouteImport,
} as any)
const CatoRoute = CatoRouteImport.update({
  id: '/cato',
  path: '/cato',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleRoute = CycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementationRoute = ImplementationRouteImport.update({
  id: '/implementation',
  path: '/implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InheritanceRoute = InheritanceRouteImport.update({
  id: '/inheritance',
  path: '/inheritance',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PoamRoute = PoamRouteImport.update({
  id: '/poam',
  path: '/poam',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepareRoute = PrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const VulnerabilitiesRoute = VulnerabilitiesRouteImport.update({
  id: '/vulnerabilities',
  path: '/vulnerabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroTrustRoute = ZeroTrustRouteImport.update({
  id: '/zero-trust',
  path: '/zero-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsIndexRoute = ControlsIndexRouteImport.update({
  id: '/controls/',
  path: '/controls/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsControlIdRoute = ControlsControlIdRouteImport.update({
  id: '/controls/$controlId',
  path: '/controls/$controlId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSystemIdRoute = SystemsSystemIdRouteImport.update({
  id: '/systems/$systemId',
  path: '/systems/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/assessments': typeof AssessmentsRoute
  '/ato': typeof AtoRoute
  '/attack': typeof AttackRoute
  '/cato': typeof CatoRoute
  '/cycle': typeof CycleRoute
  '/engine': typeof EngineRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/graph': typeof GraphRoute
  '/implementation': typeof ImplementationRoute
  '/incidents': typeof IncidentsRoute
  '/inheritance': typeof InheritanceRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/matrix': typeof MatrixRoute
  '/monitoring': typeof MonitoringRoute
  '/poam': typeof PoamRoute
  '/policy': typeof PolicyRoute
  '/prepare': typeof PrepareRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/simulate': typeof SimulateRoute
  '/supply': typeof SupplyRoute
  '/twin': typeof TwinRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/workflow': typeof WorkflowRoute
  '/zero-trust': typeof ZeroTrustRoute
  '/controls/$controlId': typeof ControlsControlIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/controls/': typeof ControlsIndexRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/assessments': typeof AssessmentsRoute
  '/ato': typeof AtoRoute
  '/attack': typeof AttackRoute
  '/cato': typeof CatoRoute
  '/cycle': typeof CycleRoute
  '/engine': typeof EngineRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/graph': typeof GraphRoute
  '/implementation': typeof ImplementationRoute
  '/incidents': typeof IncidentsRoute
  '/inheritance': typeof InheritanceRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/matrix': typeof MatrixRoute
  '/monitoring': typeof MonitoringRoute
  '/poam': typeof PoamRoute
  '/policy': typeof PolicyRoute
  '/prepare': typeof PrepareRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/simulate': typeof SimulateRoute
  '/supply': typeof SupplyRoute
  '/twin': typeof TwinRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/workflow': typeof WorkflowRoute
  '/zero-trust': typeof ZeroTrustRoute
  '/controls/$controlId': typeof ControlsControlIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/controls': typeof ControlsIndexRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRoute
  '/ask': typeof AskRoute
  '/assessments': typeof AssessmentsRoute
  '/ato': typeof AtoRoute
  '/attack': typeof AttackRoute
  '/cato': typeof CatoRoute
  '/cycle': typeof CycleRoute
  '/engine': typeof EngineRoute
  '/evidence': typeof EvidenceRoute
  '/findings': typeof FindingsRoute
  '/graph': typeof GraphRoute
  '/implementation': typeof ImplementationRoute
  '/incidents': typeof IncidentsRoute
  '/inheritance': typeof InheritanceRoute
  '/integrations': typeof IntegrationsRoute
  '/marketplace': typeof MarketplaceRoute
  '/matrix': typeof MatrixRoute
  '/monitoring': typeof MonitoringRoute
  '/poam': typeof PoamRoute
  '/policy': typeof PolicyRoute
  '/prepare': typeof PrepareRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/simulate': typeof SimulateRoute
  '/supply': typeof SupplyRoute
  '/twin': typeof TwinRoute
  '/vulnerabilities': typeof VulnerabilitiesRoute
  '/workflow': typeof WorkflowRoute
  '/zero-trust': typeof ZeroTrustRoute
  '/controls/$controlId': typeof ControlsControlIdRoute
  '/systems/$systemId': typeof SystemsSystemIdRoute
  '/controls/': typeof ControlsIndexRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/agents'
    | '/ask'
    | '/assessments'
    | '/ato'
    | '/attack'
    | '/cato'
    | '/cycle'
    | '/engine'
    | '/evidence'
    | '/findings'
    | '/graph'
    | '/implementation'
    | '/incidents'
    | '/inheritance'
    | '/integrations'
    | '/marketplace'
    | '/matrix'
    | '/monitoring'
    | '/poam'
    | '/policy'
    | '/prepare'
    | '/reports'
    | '/risk'
    | '/simulate'
    | '/supply'
    | '/twin'
    | '/vulnerabilities'
    | '/workflow'
    | '/zero-trust'
    | '/controls/$controlId'
    | '/systems/$systemId'
    | '/controls/'
    | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/admin'
    | '/agents'
    | '/ask'
    | '/assessments'
    | '/ato'
    | '/attack'
    | '/cato'
    | '/cycle'
    | '/engine'
    | '/evidence'
    | '/findings'
    | '/graph'
    | '/implementation'
    | '/incidents'
    | '/inheritance'
    | '/integrations'
    | '/marketplace'
    | '/matrix'
    | '/monitoring'
    | '/poam'
    | '/policy'
    | '/prepare'
    | '/reports'
    | '/risk'
    | '/simulate'
    | '/supply'
    | '/twin'
    | '/vulnerabilities'
    | '/workflow'
    | '/zero-trust'
    | '/controls/$controlId'
    | '/systems/$systemId'
    | '/controls'
    | '/systems'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/agents'
    | '/ask'
    | '/assessments'
    | '/ato'
    | '/attack'
    | '/cato'
    | '/cycle'
    | '/engine'
    | '/evidence'
    | '/findings'
    | '/graph'
    | '/implementation'
    | '/incidents'
    | '/inheritance'
    | '/integrations'
    | '/marketplace'
    | '/matrix'
    | '/monitoring'
    | '/poam'
    | '/policy'
    | '/prepare'
    | '/reports'
    | '/risk'
    | '/simulate'
    | '/supply'
    | '/twin'
    | '/vulnerabilities'
    | '/workflow'
    | '/zero-trust'
    | '/controls/$controlId'
    | '/systems/$systemId'
    | '/controls/'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRoute
  AskRoute: typeof AskRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AtoRoute: typeof AtoRoute
  AttackRoute: typeof AttackRoute
  CatoRoute: typeof CatoRoute
  CycleRoute: typeof CycleRoute
  EngineRoute: typeof EngineRoute
  EvidenceRoute: typeof EvidenceRoute
  FindingsRoute: typeof FindingsRoute
  GraphRoute: typeof GraphRoute
  ImplementationRoute: typeof ImplementationRoute
  IncidentsRoute: typeof IncidentsRoute
  InheritanceRoute: typeof InheritanceRoute
  IntegrationsRoute: typeof IntegrationsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MatrixRoute: typeof MatrixRoute
  MonitoringRoute: typeof MonitoringRoute
  PoamRoute: typeof PoamRoute
  PolicyRoute: typeof PolicyRoute
  PrepareRoute: typeof PrepareRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SimulateRoute: typeof SimulateRoute
  SupplyRoute: typeof SupplyRoute
  TwinRoute: typeof TwinRoute
  VulnerabilitiesRoute: typeof VulnerabilitiesRoute
  WorkflowRoute: typeof WorkflowRoute
  ZeroTrustRoute: typeof ZeroTrustRoute
  ControlsControlIdRoute: typeof ControlsControlIdRoute
  SystemsSystemIdRoute: typeof SystemsSystemIdRoute
  ControlsIndexRoute: typeof ControlsIndexRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ato': {
      id: '/ato'
      path: '/ato'
      fullPath: '/ato'
      preLoaderRoute: typeof AtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack': {
      id: '/attack'
      path: '/attack'
      fullPath: '/attack'
      preLoaderRoute: typeof AttackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cato': {
      id: '/cato'
      path: '/cato'
      fullPath: '/cato'
      preLoaderRoute: typeof CatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle': {
      id: '/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof CycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementation': {
      id: '/implementation'
      path: '/implementation'
      fullPath: '/implementation'
      preLoaderRoute: typeof ImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inheritance': {
      id: '/inheritance'
      path: '/inheritance'
      fullPath: '/inheritance'
      preLoaderRoute: typeof InheritanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poam': {
      id: '/poam'
      path: '/poam'
      fullPath: '/poam'
      preLoaderRoute: typeof PoamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prepare': {
      id: '/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof PrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vulnerabilities': {
      id: '/vulnerabilities'
      path: '/vulnerabilities'
      fullPath: '/vulnerabilities'
      preLoaderRoute: typeof VulnerabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero-trust': {
      id: '/zero-trust'
      path: '/zero-trust'
      fullPath: '/zero-trust'
      preLoaderRoute: typeof ZeroTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/': {
      id: '/controls/'
      path: '/controls'
      fullPath: '/controls/'
      preLoaderRoute: typeof ControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/$controlId': {
      id: '/controls/$controlId'
      path: '/controls/$controlId'
      fullPath: '/controls/$controlId'
      preLoaderRoute: typeof ControlsControlIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$systemId': {
      id: '/systems/$systemId'
      path: '/systems/$systemId'
      fullPath: '/systems/$systemId'
      preLoaderRoute: typeof SystemsSystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRoute,
  AskRoute: AskRoute,
  AssessmentsRoute: AssessmentsRoute,
  AtoRoute: AtoRoute,
  AttackRoute: AttackRoute,
  CatoRoute: CatoRoute,
  CycleRoute: CycleRoute,
  EngineRoute: EngineRoute,
  EvidenceRoute: EvidenceRoute,
  FindingsRoute: FindingsRoute,
  GraphRoute: GraphRoute,
  ImplementationRoute: ImplementationRoute,
  IncidentsRoute: IncidentsRoute,
  InheritanceRoute: InheritanceRoute,
  IntegrationsRoute: IntegrationsRoute,
  MarketplaceRoute: MarketplaceRoute,
  MatrixRoute: MatrixRoute,
  MonitoringRoute: MonitoringRoute,
  PoamRoute: PoamRoute,
  PolicyRoute: PolicyRoute,
  PrepareRoute: PrepareRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SimulateRoute: SimulateRoute,
  SupplyRoute: SupplyRoute,
  TwinRoute: TwinRoute,
  VulnerabilitiesRoute: VulnerabilitiesRoute,
  WorkflowRoute: WorkflowRoute,
  ZeroTrustRoute: ZeroTrustRoute,
  ControlsControlIdRoute: ControlsControlIdRoute,
  SystemsSystemIdRoute: SystemsSystemIdRoute,
  ControlsIndexRoute: ControlsIndexRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
